export const ACTIONS = {
  ADD_BOX: 'ADD_BOX',
  SELECT_BOX: 'SELECT_BOX',
  DELETE_BOX: 'DELETE_BOX',
  EDIT_BOX: 'EDIT_BOX',
  ADD_SCREEN: 'ADD_SCREEN',
  DELETE_SCREEN: 'DELETE_SCREEN',
  EDIT_SCREEN: 'EDIT_SCREEN',
};

export const GRID_SIZE = 10;

export const CLICK_LENGTH_MS = 200;

export const ANIMATION_DURATION = 150;

export const BREAKPOINT_SIZES = {
  SMALL_MED: 480,
  MED_LARGE: 880,
  LARGE_JUMBO: 1120,
};

export const BREAKPOINTS = {
  SMALL_ONLY: `@media (max-width: ${BREAKPOINT_SIZES.SMALL_MED}px)`,
  MEDIUM_UP: `@media (min-width: ${BREAKPOINT_SIZES.SMALL_MED}px)`,
  LARGE_UP: `@media (min-width: ${BREAKPOINT_SIZES.MED_LARGE}px)`,
  JUMBO_UP: `@media (min-width: ${BREAKPOINT_SIZES.LARGE_JUMBO}px)`,
};

export const DIMENSIONS = {
  LAYOUT: {
    HEADER_HEIGHT: 60,
    TOOLBAR_WIDTH: 120,
  },
  TEXT: {
    HEADING_1: 40,
    HEADING_2: 30,
    HEADING_3: 20, // TODO: no idea, just messing around
  },
};

// palette generated by: http://www.materialpalette.com/blue/deep-orange
export const COLORS = {
  PRIMARY_DARK: '#1976D2', // dark blue
  PRIMARY: '#2196F3', // blue
  PRIMARY_LIGHT: '#BBDEFB', // light blue
  ACCENT: '#FF5722', // orange
  GRAY_DARK: '#212121',
  GRAY: '#727272',
  GRAY_LIGHT: '#B6B6B6',
  WHITE: '#FFFFFF',
};
